[package]
name = "bevy_maze"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5"
bevy_prototype_lyon = "0.3.1"
rand = "0.8.4"
